/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinha;

import java.awt.Font;

/**
 *
 * @author daldantas
 */
public class Adivinha extends javax.swing.JFrame {

    /**
     * Creates new form Adivinha
     */
    public Adivinha() {
        initComponents();
        lblFrase.setFont(new Font ("Ubuntu", Font.BOLD, 18));
        lblFrase.setText("<html><center>Adivinhe o número <br>que estou pensando,<br> entre <i style='font-size:1.5em'>1</i> e <i style='font-size:1.5em'>5</i> !</center><html>");
        // Palpite show
        txtN.setVisible(true);
        btnOk.setVisible(true);
        // Tela resultados hide
        lblPensou.setVisible(false);
        lblPalpite.setVisible(false);
        lblOutraVez.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOutraVez = new javax.swing.JButton();
        lblFrase = new javax.swing.JLabel();
        lblbalao = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        txtN = new javax.swing.JSpinner();
        btnOk = new javax.swing.JButton();
        lblPalpite = new javax.swing.JLabel();
        lblPensou = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOutraVez.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblOutraVez.setText("Outra vez");
        lblOutraVez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblOutraVezActionPerformed(evt);
            }
        });
        getContentPane().add(lblOutraVez, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 150, 80));

        lblFrase.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("...");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 190, 110));

        lblbalao.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblbalao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao.png"))); // NOI18N
        getContentPane().add(lblbalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 410, 230));

        lblGenio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adivinha.png"))); // NOI18N
        lblGenio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 290, 450));

        txtN.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtN.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 70, 80));

        btnOk.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 70, 80));

        lblPalpite.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        lblPalpite.setText("-");
        getContentPane().add(lblPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 260, 40));

        lblPensou.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        lblPensou.setText("-");
        getContentPane().add(lblPensou, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 260, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        int rand = (int) ( 5 * Math.random() + 1);
        int N = (int) txtN.getValue();
        boolean palpiteB = N == rand;
        String genio = palpiteB ? "/imagens/acertou.png" : "/imagens/errou.png";
        lblFrase.setText(palpiteB ? "Acertou, pura sorte !" : "Erroooou !");
        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource(genio)));
         // Palpite hide
        txtN.setVisible(false);
        btnOk.setVisible(false);
        // Tela resultados  set
        String palpite = Integer.toString(N);
        String pensou = Integer.toString(rand);
        palpite += " foi o palpite.";
        pensou += " o gênio pensou.";
        lblPalpite.setText(palpite);
        lblPensou.setText(pensou);
         // Tela resultados show
         lblPalpite.setVisible(true);
        lblPensou.setVisible(true);
        lblOutraVez.setVisible(true);
    }//GEN-LAST:event_btnOkActionPerformed

    private void lblOutraVezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblOutraVezActionPerformed
        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adivinha.png")));
        lblFrase.setText("<html><center>Adivinhe o número <br>que estou pensando,<br> entre <b>1</b> e <b>5</b> !</center><html>");
        // Palpite show
        txtN.setVisible(true);
        btnOk.setVisible(true);
        // Tela resultados hide
        lblPensou.setVisible(false);
        lblPalpite.setVisible(false);
        lblOutraVez.setVisible(false);
    }//GEN-LAST:event_lblOutraVezActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adivinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JButton lblOutraVez;
    private javax.swing.JLabel lblPalpite;
    private javax.swing.JLabel lblPensou;
    private javax.swing.JLabel lblbalao;
    private javax.swing.JSpinner txtN;
    // End of variables declaration//GEN-END:variables
}
